### ISSUE TITLE
你好，开发者！

### ISSUE THREAD

**Issue by Zxido** [repic-app/desktop-client#1]
你好，开发者！
软件很好用，但是我安装后还是显示为0.1.1版本，没有插件安装提示，没有更新按钮，请问该如何解决
![PixPin_2023-11-25_01-00-33](https://github.com/repic-app/desktop-client/assets/124896173/858f717c-f641-47c2-843b-0c119a6716c1)
![PixPin_2023-11-25_01-00-40](https://github.com/repic-app/desktop-client/assets/124896173/40faf4a4-6bd2-4597-abc1-cfdac5a0f07b)

**Comment by margox** [comment]
可能是之前打的windows版本的包是旧的～ 你可以打开插件目录，然后把下面这些repo都下载下来解压放到插件目录试试：
https://github.com/orgs/repic-app/repositories
<img width="778" alt="image" src="https://github.com/repic-app/desktop-client/assets/7866354/74f50186-2576-4b3e-8282-22bd92b908f6">

我晚点找个win电脑试试看～ 好几年没照顾过这个项目了，感谢关注～

**Comment by Zxido** [comment]
谢谢，已经解决了，成功安装了插件
